name: CI - PR Front

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Admin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install project dependencies (yarn)
        run: yarn install --frozen-lockfile

      - name: ESLint Cache
        uses: actions/cache@v2
        id: eslint-cache
        with:
          path: .cache/eslint
          key: ${{ runner.os }}-eslint

      - name: Code analysis (ESLint) and style-guide analysis (Prettier)
        run: yarn test:lint
